workflow renaming

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -8,9 +8,13 @@ jobs:
     validate:
         runs-on: ubuntu-latest
 
+        permissions:
+            contents: write # Allows actions to write to repository contents
+            pull-requests: write # Allows actions to write to pull requests
+
         steps:
             - name: Checkout repository
-              uses: actions/checkout@v4 # Updated to the latest version
+              uses: actions/checkout@v4
 
             - name: Fetch main branch changes
               run: git fetch origin main
@@ -20,56 +24,52 @@ jobs:
 
             - name: Get PR branch name
               id: pr_branch_name
-              run: echo "branch_name=$(git rev-parse --abbrev-ref pr_branch)" >> $GITHUB_ENV # Updated to use environment files
+              run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref pr_branch)" >> $GITHUB_ENV
 
             - name: Diff changes
-              run: git diff --name-status origin/main...${{ env.branch_name }} > diff_output.txt
+              run: git diff origin/main...$BRANCH_NAME -- > diff_output.txt
 
-            - name: Check for unauthorized chainId folder creation
+            - name: Identify deleted lines
+              run: grep '^-' diff_output.txt > deleted_lines.txt
+
+            - name: Check deleted lines attribution
+              run: |
+                  while IFS= read -r line; do
+                    file=$(echo "$line" | cut -d ' ' -f 2)
+                    original_commit=$(git blame -L "/$line/" origin/main -- "$file" | cut -d ' ' -f 1 | head -n 1)
+                    original_author=$(git show -s --format='%an' $original_commit)
+                    deleting_author=$(git show -s --format='%an' HEAD)
+                    if [ "$original_author" != "$deleting_author" ]; then
+                      echo "Deleted line '$line' was originally created by a different contributor"
+                      exit 1
+                    fi
+                  done < deleted_lines.txt
+
+            - name: Validate folder structure and files
               run: |
                   CHAIN_ID_REGEX='^[0-9]+$'
                   TOKEN_ADDRESS_REGEX='^0x[a-fA-F0-9]{40}$'
 
-                  while IFS=$'\t' read -r status file; do
+                  PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
+
+                  for file in $(git diff --name-only origin/main...$BRANCH_NAME); do
                     IFS='/' read -r -a path_parts <<< "$file"
 
-                    if [[ ${#path_parts[@]} -eq 1 ]]; then
-                      if [[ ${path_parts[0]} =~ $CHAIN_ID_REGEX ]]; then
-                        echo "Unauthorized creation of chainId folder: ${path_parts[0]}"
-                        exit 1
-                      fi
-                    fi
-
-                    if [[ ${#path_parts[@]} -eq 2 ]]; then
-                      if [[ ! ${path_parts[1]} =~ $TOKEN_ADDRESS_REGEX ]]; then
-                        echo "Invalid token address folder: ${path_parts[1]}"
-                        exit 1
-                      fi
-                    fi
-                  done < diff_output.txt
-
-            - name: Check for unauthorized file modifications
-              run: |
-                  while IFS=$'\t' read -r status file; do
-                    IFS='/' read -r -a path_parts <<< "$file"
-
-                    # Ensure only files inside token_address folders are modified
-                    if [[ ${#path_parts[@]} -eq 2 && $status != "A" ]]; then
-                      echo "Files can only be modified inside token_address folders"
+                    if [[ ${#path_parts[@]} -lt 2 ]]; then
+                      echo "Invalid path structure: $file"
                       exit 1
                     fi
 
-                    # Ensure only the creator of the folder can modify or add files to it
-                    if [[ ${#path_parts[@]} -ge 2 ]]; then
-                      folder_creator=$(git log --pretty=format:"%an" --reverse -- "${path_parts[0]}/${path_parts[1]}" | head -n 1)
-                      pr_author=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
-                      if [[ "$folder_creator" != "$pr_author" ]]; then
-                        echo "Unauthorized modification by $pr_author in folder: ${path_parts[0]}/${path_parts[1]}"
-                        exit 1
-                      fi
+                    if ! [[ ${path_parts[0]} =~ $CHAIN_ID_REGEX ]]; then
+                      echo "Invalid chain ID folder: ${path_parts[0]}"
+                      exit 1
                     fi
 
-                    # Ensure only valid files are added
+                    if ! [[ ${path_parts[1]} =~ $TOKEN_ADDRESS_REGEX ]]; then
+                      echo "Invalid token address folder: ${path_parts[1]}"
+                      exit 1
+                    fi
+
                     if [[ ${#path_parts[@]} -eq 3 ]]; then
                       case "${path_parts[2]}" in
                         info.json)
@@ -78,8 +78,8 @@ jobs:
                             exit 1
                           fi
                           ;;
-                        logo.svg)
-                          if ! file "$file" | grep -q 'SVG'; then
+                        logo.png|logo.jpg|logo.jpeg|logo.svg)
+                          if ! file "$file" | grep -qE 'image|SVG'; then
                             echo "Invalid logo file: $file"
                             exit 1
                           fi
@@ -90,17 +90,12 @@ jobs:
                           ;;
                       esac
                     fi
-                  done < diff_output.txt
 
-            - name: Ensure no files are added to the chainId folder path
-              run: |
-                  while IFS=$'\t' read -r status file; do
-                    IFS='/' read -r -a path_parts <<< "$file"
-                    if [[ ${#path_parts[@]} -eq 1 ]]; then
-                      echo "Files cannot be added directly to the chainId folder path"
+                    if git log --pretty=format:"%an" "$file" | grep -v "$PR_AUTHOR" > /dev/null; then
+                      echo "Unauthorized change by $PR_AUTHOR to file: $file"
                       exit 1
                     fi
-                  done < diff_output.txt
+                  done
 
             - name: Auto-merge PR
               if: success()
@@ -109,10 +104,15 @@ jobs:
                   github-token: ${{ secrets.GITHUB_TOKEN }}
                   script: |
                       const pull_number = context.payload.pull_request.number;
-                      const response = await github.rest.pulls.merge({
-                        owner: context.repo.owner,
-                        repo: context.repo.repo,
-                        pull_number: pull_number,
-                        merge_method: 'squash'
-                      });
-                      console.log(response);
+                      try {
+                        const response = await github.rest.pulls.merge({
+                          owner: context.repo.owner,
+                          repo: context.repo.repo,
+                          pull_number: pull_number,
+                          merge_method: 'squash'
+                        });
+                        console.log('Merge response:', response);
+                      } catch (error) {
+                        console.error('Failed to merge PR:', error);
+                        process.exit(1); // Fail the workflow if merging fails
+                      }
